apiVersion: v1
kind: Service
metadata:
  name: cicd-gitops-jenkins-101
spec:
  type: ClusterIP
  selector:
    app: cicd-gitops-jenkins-101
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
