apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-gitops-jenkins-101-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ponpond/cicd-gitops-jenkins-101.git
    targetRevision: main
    path: gitops/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-staging
  # Staging: fully automated GitOps. ArgoCD reconciles every commit.
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
